=== r351574nc3/kfs-overlay-reference/web/src/main/resources/xsd/fp/procurementCard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright 2007-2008 The Kuali Foundation
 
 Licensed under the Educational Community License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
 http://www.opensource.org/licenses/ecl2.php
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<xsd:schema elementFormDefault="qualified"
    targetNamespace="http://www.kuali.org/kfs/fp/procurementCard"
    xmlns:kfs="http://www.kuali.org/kfs/sys/types"
    xmlns:dd="http://www.kuali.org/kfs/sys/ddTypes"
    xmlns="http://www.kuali.org/kfs/fp/procurementCard" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:import namespace="http://www.kuali.org/kfs/sys/types" schemaLocation="@externalizable.static.content.url@/xsd/sys/types.xsd" />
    <xsd:import namespace="http://www.kuali.org/kfs/sys/ddTypes" schemaLocation="@externalizable.static.content.url@/xsd/sys/ddTypes.xsd" />

    <xsd:element name="transactionCreditCardNumber" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionCreditCardNumber}"/>
    <xsd:element name="financialDocumentTotalAmount" type="${xsd:decimal,dd:ProcurementCardTransaction.financialDocumentTotalAmount}"/>
    <xsd:element name="transactionDebitCreditCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionDebitCreditCode}"/>
    <xsd:element name="chartOfAccountsCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.chartOfAccountsCode}"/>
    <xsd:element name="accountNumber" type="${xsd:normalizedString,dd:ProcurementCardTransaction.accountNumber}"/>
    <xsd:element name="subAccountNumber" type="${xsd:normalizedString,dd:ProcurementCardTransaction.subAccountNumber}"/>
    <xsd:element name="financialObjectCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.financialObjectCode}"/>
    <xsd:element name="financialSubObjectCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.financialSubObjectCode}"/>
    <xsd:element name="projectCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.projectCode}"/>
    <xsd:element name="transactionCycleStartDate" type="${xsd:date,dd:ProcurementCardTransaction.transactionCycleStartDate}"/>
    <xsd:element name="transactionCycleEndDate" type="${xsd:date,dd:ProcurementCardTransaction.transactionCycleEndDate}"/>
    <xsd:element name="cardHolderName" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardHolderName}"/>
    <xsd:element name="transactionDate" type="${xsd:date,dd:ProcurementCardTransaction.transactionDate}"/>
    <xsd:element name="transactionReferenceNumber" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionReferenceNumber}"/>
    <xsd:element name="transactionMerchantCategoryCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionMerchantCategoryCode}"/>
    <xsd:element name="transactionPostingDate" type="${xsd:date,dd:ProcurementCardTransaction.transactionPostingDate}"/>
    <xsd:element name="transactionOriginalCurrencyCode" type="${xsd:date,dd:ProcurementCardTransaction.transactionOriginalCurrencyCode}"/>
    <xsd:element name="transactionBillingCurrencyCode" type="${xsd:date,dd:ProcurementCardTransaction.transactionBillingCurrencyCode}"/>
    <xsd:element name="transactionOriginalCurrencyAmount" type="${xsd:decimal,dd:ProcurementCardTransaction.transactionOriginalCurrencyAmount}"/>
    <xsd:element name="transactionCurrencyExchangeRate" type="${xsd:decimal,dd:ProcurementCardTransaction.transactionCurrencyExchangeRate}"/>
    <xsd:element name="transactionSettlementAmount" type="${xsd:decimal,dd:ProcurementCardTransaction.transactionSettlementAmount}"/>
    <xsd:element name="transactionSalesTaxAmount" type="${xsd:decimal,dd:ProcurementCardTransaction.transactionSalesTaxAmount}"/>
    <xsd:element name="transactionTaxExemptIndicator" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionTaxExemptIndicator}"/>
    <xsd:element name="transactionPurchaseIdentifierIndicator" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionPurchaseIdentifierIndicator}"/>
    <xsd:element name="transactionPurchaseIdentifierDescription" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionPurchaseIdentifierDescription}"/>
    <xsd:element name="transactionUnitContactName" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionUnitContactName}"/>
    <xsd:element name="transactionTravelAuthorizationCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionTravelAuthorizationCode}"/>
    <xsd:element name="transactionPointOfSaleCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.transactionPointOfSaleCode}"/>
    <xsd:element name="vendorName" type="${xsd:normalizedString,dd:ProcurementCardTransaction.vendorName}"/>
    <xsd:element name="vendorLine1Address" type="${xsd:normalizedString,dd:ProcurementCardTransaction.vendorLine1Address}"/>
    <xsd:element name="vendorLine2Address" type="${xsd:normalizedString,dd:ProcurementCardTransaction.vendorLine2Address}"/>
    <xsd:element name="vendorCityName" type="${xsd:normalizedString,dd:ProcurementCardTransaction.vendorCityName}"/>
    <xsd:element name="vendorStateCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.vendorStateCode}"/>
    <xsd:element name="vendorZipCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.vendorZipCode}"/>
    <xsd:element name="vendorOrderNumber" type="${xsd:normalizedString,dd:ProcurementCardTransaction.vendorOrderNumber}"/>
    <xsd:element name="visaVendorIdentifier" type="${xsd:normalizedString,dd:ProcurementCardTransaction.visaVendorIdentifier}"/>
    <xsd:element name="cardHolderAlternateName" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardHolderAlternateName}"/>
    <xsd:element name="cardHolderLine1Address" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardHolderLine1Address}"/>
    <xsd:element name="cardHolderLine2Address" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardHolderLine2Address}"/>
    <xsd:element name="cardHolderCityName" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardHolderCityName}"/>
    <xsd:element name="cardHolderStateCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardHolderStateCode}"/>
    <xsd:element name="cardHolderZipCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardHolderZipCode}"/>
    <xsd:element name="cardHolderWorkPhoneNumber" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardHolderWorkPhoneNumber}"/>
    <xsd:element name="cardLimit" type="${xsd:decimal,dd:ProcurementCardTransaction.cardLimit}"/>
    <xsd:element name="cardCycleAmountLimit" type="${xsd:decimal,dd:ProcurementCardTransaction.cardCycleAmountLimit}"/>
    <xsd:element name="cardCycleVolumeLimit" type="${xsd:decimal,dd:ProcurementCardTransaction.cardCycleVolumeLimit}"/>
    <xsd:element name="cardStatusCode" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardStatusCode}"/>
    <xsd:element name="cardNoteText" type="${xsd:normalizedString,dd:ProcurementCardTransaction.cardNoteText}"/>
 
    <!-- definition of complex type elements -->
    <xsd:element name="transactions">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="transaction"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="transaction">
        <xsd:complexType>
            <xsd:sequence>
               <xsd:element maxOccurs="1" minOccurs="1" ref="transactionCreditCardNumber" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="financialDocumentTotalAmount" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="transactionDebitCreditCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="chartOfAccountsCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="accountNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="subAccountNumber" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="financialObjectCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="financialSubObjectCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="projectCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionCycleStartDate" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionCycleEndDate" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardHolderName" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="transactionDate" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionReferenceNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionMerchantCategoryCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionPostingDate" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionOriginalCurrencyCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionBillingCurrencyCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionOriginalCurrencyAmount" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionCurrencyExchangeRate" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionSettlementAmount" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionSalesTaxAmount" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionTaxExemptIndicator" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionPurchaseIdentifierIndicator" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionPurchaseIdentifierDescription" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionUnitContactName" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionTravelAuthorizationCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionPointOfSaleCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="vendorName" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="vendorLine1Address" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="vendorLine2Address" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="vendorCityName" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="vendorStateCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="vendorZipCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="vendorOrderNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="visaVendorIdentifier" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardHolderAlternateName" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardHolderLine1Address" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardHolderLine2Address" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardHolderCityName" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardHolderStateCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardHolderZipCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardHolderWorkPhoneNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardLimit" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardCycleAmountLimit" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardCycleVolumeLimit" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardStatusCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="cardNoteText" />
             </xsd:sequence>  
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== r351574nc3/kfs-overlay-reference/config/src/main/resources/work/staging/fp/procurementCard/fieldsInWrongOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Copyright 2005-2007 The Kuali Foundation
	
	Licensed under the Educational Community License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	http://www.opensource.org/licenses/ecl2.php
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->
<transactions xmlns="http://www.kuali.org/kfs/fp/procurementCard"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.kuali.org/kfs/fp/procurementCard @externalizable.static.content.url@/xsd/fp/procurementCard.xsd" >

	<transaction>
		<transactionCreditCardNumber>999911112222333</transactionCreditCardNumber>
		<financialDocumentTotalAmount>30.27</financialDocumentTotalAmount>
		<transactionDebitCreditCode>D</transactionDebitCreditCode>
		<chartOfAccountsCode>BL</chartOfAccountsCode>
		<accountNumber>4631654</accountNumber>
		<financialObjectCode>4190</financialObjectCode>
		<transactionCycleStartDate>2006-03-02</transactionCycleStartDate>
		<transactionCycleEndDate>2006-03-02</transactionCycleEndDate>
		<cardHolderName>BARBARA TRUESDELL</cardHolderName>
		<transactionDate>2006-03-01</transactionDate>
		<transactionReferenceNumber>55417346061640610702687</transactionReferenceNumber>
		<transactionMerchantCategoryCode>5192</transactionMerchantCategoryCode>
		<transactionPostingDate>2006-03-01</transactionPostingDate>
		<vendorName>IMU BOOKSTORE</vendorName>
	</transaction>


	<transaction>
		<cardHolderName>IUPUI JAGS BOOKSTORES</cardHolderName>
		<transactionDate>2006-01-02</transactionDate>
		<transactionReferenceNumber>432866002000132935937</transactionReferenceNumber>
		<transactionMerchantCategoryCode>5192</transactionMerchantCategoryCode>
		<transactionPostingDate>2006-01-02</transactionPostingDate>
		<vendorName>AMZ*AMAZON PAYMENTS</vendorName>
		<transactionCreditCardNumber>4444876757777111</transactionCreditCardNumber>
		<financialDocumentTotalAmount>1.46</financialDocumentTotalAmount>
		<transactionDebitCreditCode>D</transactionDebitCreditCode>
		<chartOfAccountsCode>BL</chartOfAccountsCode>
		<accountNumber>4631654</accountNumber>
		<financialObjectCode>4190</financialObjectCode>
		<transactionCycleStartDate>2006-01-03</transactionCycleStartDate>
		<transactionCycleEndDate>2006-01-03</transactionCycleEndDate>
	</transaction>
</transactions>

=== r351574nc3/kfs-overlay-reference/config/target/classes/work/staging/fp/procurementCard/transactionWithExtraFields.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Copyright 2005-2007 The Kuali Foundation
	
	Licensed under the Educational Community License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	http://www.opensource.org/licenses/ecl2.php
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->
<transactions xmlns="http://www.kuali.org/kfs/fp/procurementCard"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.kuali.org/kfs/fp/procurementCard @externalizable.static.content.url@/xsd/fp/procurementCard.xsd" >

	<transaction>
		<transactionCreditCardNumber>999911112222333</transactionCreditCardNumber>
		<financialDocumentTotalAmount>11.55</financialDocumentTotalAmount>
		<transactionDebitCreditCode>D</transactionDebitCreditCode>
		<chartOfAccountsCode>BL</chartOfAccountsCode>
		<accountNumber>4631654</accountNumber>
		<financialObjectCode>4190</financialObjectCode>
		<transactionCycleStartDate>2006-02-20</transactionCycleStartDate>
		<transactionCycleEndDate>2006-02-20</transactionCycleEndDate>
		<cardHolderName>Molecular Structure Center</cardHolderName>
		<transactionDate>2006-02-17</transactionDate>
		<transactionReferenceNumber>554173460487304813890</transactionReferenceNumber>
		<transactionMerchantCategoryCode>7622</transactionMerchantCategoryCode>
		<transactionPostingDate>2006-02-17</transactionPostingDate>
		<vendorName>STANSIFER RADIO CO</vendorName>
	</transaction>

	<transaction>
		<transactionCreditCardNumber>999911112222333</transactionCreditCardNumber>
		<financialDocumentTotalAmount>30.27</financialDocumentTotalAmount>
		<transactionDebitCreditCode>D</transactionDebitCreditCode>
		<chartOfAccountsCode>BL</chartOfAccountsCode>
		<accountNumber>4631654</accountNumber>
		<subAccountNumber>ADV</subAccountNumber>
		<financialObjectCode>4190</financialObjectCode>
        <!-- <financialSubObjectCode>Need a value here</financialSubObjectCode> -->
        <projectCode>BOB</projectCode>
		<transactionCycleStartDate>2006-03-02</transactionCycleStartDate>
		<transactionCycleEndDate>2006-03-02</transactionCycleEndDate>
		<cardHolderName>BARBARA TRUESDELL</cardHolderName>
		<transactionDate>2006-03-01</transactionDate>
		<transactionReferenceNumber>55417346061640610702687</transactionReferenceNumber>
		<transactionMerchantCategoryCode>5192</transactionMerchantCategoryCode>
		<transactionPostingDate>2006-03-01</transactionPostingDate>
		<vendorName>IMU BOOKSTORE</vendorName>
		<vendorLine1Address>IU Memorial Union</vendorLine1Address>
        <vendorLine2Address>Mezz Level</vendorLine2Address>
        <vendorCityName>Bloomington</vendorCityName>
        <vendorStateCode>IN</vendorStateCode>
        <vendorZipCode>47408</vendorZipCode>
        <vendorOrderNumber>12345</vendorOrderNumber>
        <visaVendorIdentifier>Don't know</visaVendorIdentifier>
        <cardHolderAlternateName>Big Red</cardHolderAlternateName>
        <cardHolderLine1Address>Somewhere</cardHolderLine1Address>
        <cardHolderLine2Address>Some building</cardHolderLine2Address>
        <cardHolderCityName>Bloom</cardHolderCityName>
        <cardHolderStateCode>IN</cardHolderStateCode>
        <cardHolderZipCode>47401</cardHolderZipCode>
        <cardHolderWorkPhoneNumber>8125555555</cardHolderWorkPhoneNumber>
        <cardLimit>100</cardLimit>
        <cardCycleAmountLimit>100</cardCycleAmountLimit>
        <cardCycleVolumeLimit>100</cardCycleVolumeLimit>
        <cardStatusCode>A</cardStatusCode>
        <cardNoteText>Hi</cardNoteText>
	</transaction>
</transactions>

=== r351574nc3/kfs-overlay-reference/config/src/main/resources/work/staging/fp/procurementCard/badChartData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Copyright 2005-2008 The Kuali Foundation
	
	Licensed under the Educational Community License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	http://www.opensource.org/licenses/ecl2.php
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->
<transactions xmlns="http://www.kuali.org/kfs/fp/procurementCard"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.kuali.org/kfs/fp/procurementCard @externalizable.static.content.url@/xsd/fp/procurementCard.xsd" >

	<transaction>
		<transactionCreditCardNumber>99991111200</transactionCreditCardNumber>
		<financialDocumentTotalAmount>11.55</financialDocumentTotalAmount>
		<transactionDebitCreditCode>D</transactionDebitCreditCode>
		<chartOfAccountsCode>AA</chartOfAccountsCode>
		<accountNumber>9999999</accountNumber>
		<financialObjectCode>9999</financialObjectCode>
		<transactionCycleStartDate>2006-02-20</transactionCycleStartDate>
		<transactionCycleEndDate>2006-02-20</transactionCycleEndDate>
		<cardHolderName>Molecular Structure Center</cardHolderName>
		<transactionDate>2006-02-17</transactionDate>
		<transactionReferenceNumber>554173460487304813890</transactionReferenceNumber>
		<transactionMerchantCategoryCode>7622</transactionMerchantCategoryCode>
		<transactionPostingDate>2006-02-17</transactionPostingDate>
		<vendorName>STANSIFER RADIO CO</vendorName>
	</transaction>
</transactions>
