=== r351574nc3/kfs-overlay-reference/web/src/main/resources/xsd/gl/collector.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright 2007-2009 The Kuali Foundation
 
 Licensed under the Educational Community License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
 http://www.opensource.org/licenses/ecl2.php
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<xsd:schema elementFormDefault="qualified"
    targetNamespace="http://www.kuali.org/kfs/gl/collector"
    xmlns:kfs="http://www.kuali.org/kfs/sys/types"
    xmlns:dd="http://www.kuali.org/kfs/sys/ddTypes"
    xmlns="http://www.kuali.org/kfs/gl/collector" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:import namespace="http://www.kuali.org/kfs/sys/types" schemaLocation="@externalizable.static.content.url@/xsd/sys/types.xsd" />
    <xsd:import namespace="http://www.kuali.org/kfs/sys/ddTypes" schemaLocation="@externalizable.static.content.url@/xsd/sys/ddTypes.xsd" />
 
    <!-- header fields -->   
    <xsd:element name="organizationCode" type="${xsd:normalizedString,dd:CollectorBatch.organizationCode}"/>
    <xsd:element name="transmissionDate" type="${xsd:date,dd:CollectorBatch.transmissionDate}"/>
   	<xsd:element name="batchSequenceNumber" type="${xsd:integer,dd:CollectorBatch.batchSequenceNumber}"/>
   	<xsd:element name="personUserId" type="${xsd:normalizedString,dd:CollectorBatch.personUserID}"/>
   	<xsd:element name="emailAddress" type="${xsd:normalizedString,dd:CollectorBatch.emailAddress}"/>
	<xsd:element name="campusCode" type="${xsd:normalizedString,dd:CollectorBatch.campusCode}"/>
	<xsd:element name="phoneNumber" type="${xsd:normalizedString,dd:CollectorBatch.phoneNumber}"/>
	<xsd:element name="mailingAddress" type="${xsd:normalizedString,dd:CollectorBatch.mailingAddress}"/>
	<xsd:element name="departmentName" type="${xsd:normalizedString,dd:CollectorBatch.departmentName}"/>
   
       <!-- glEntry fields -->
    <xsd:element name="universityFiscalYear" type="${xsd:normalizedString,dd:OriginEntryFull.universityFiscalYear}"/>
    <xsd:element name="chartOfAccountsCode" type="${xsd:normalizedString,dd:OriginEntryFull.chartOfAccountsCode}"/>
    <xsd:element name="accountNumber" type="${xsd:normalizedString,dd:OriginEntryFull.accountNumber}"/>
    <xsd:element name="subAccountNumber" type="${xsd:normalizedString,dd:OriginEntryFull.subAccountNumber}"/>
    <xsd:element name="objectCode" type="${xsd:normalizedString,dd:OriginEntryFull.financialObjectCode}"/>
    <xsd:element name="subObjectCode" type="${xsd:normalizedString,dd:OriginEntryFull.financialSubObjectCode}"/>
    <xsd:element name="balanceTypeCode" type="${xsd:normalizedString,dd:OriginEntryFull.financialBalanceTypeCode}"/>
    <xsd:element name="objectTypeCode" type="${xsd:normalizedString,dd:OriginEntryFull.financialObjectTypeCode}"/>
    <xsd:element name="universityFiscalAccountingPeriod" type="${xsd:normalizedString,dd:OriginEntryFull.universityFiscalPeriodCode}"/>
    <xsd:element name="documentTypeCode" type="${xsd:normalizedString,dd:OriginEntryFull.financialDocumentTypeCode}"/>
    <xsd:element name="originationCode" type="${xsd:normalizedString,dd:OriginEntryFull.financialSystemOriginationCode}"/>
    <xsd:element name="documentNumber" type="${xsd:normalizedString,dd:OriginEntryFull.documentNumber}"/>
    <xsd:element name="transactionEntrySequenceId" type="${xsd:integer,dd:OriginEntryFull.transactionLedgerEntrySequenceNumber}"/>
    <xsd:element name="transactionLedgerEntryDescription" type="${xsd:normalizedString,dd:OriginEntryFull.transactionLedgerEntryDescription}"/>
    <xsd:element name="transactionLedgerEntryAmount" type="${xsd:decimal,dd:OriginEntryFull.transactionLedgerEntryAmount}"/>
    <xsd:element name="debitOrCreditCode" type="${xsd:normalizedString,dd:OriginEntryFull.transactionDebitCreditCode}"/>
    <xsd:element name="transactionDate" type="${xsd:date,dd:OriginEntryFull.transactionDate}"/>
    <xsd:element name="organizationDocumentNumber" type="${xsd:normalizedString,dd:OriginEntryFull.organizationDocumentNumber}"/>
    <xsd:element name="projectCode" type="${xsd:normalizedString,dd:OriginEntryFull.projectCode}"/>
    <xsd:element name="organizationReferenceId" type="${xsd:normalizedString,dd:OriginEntryFull.organizationReferenceId}"/>
    <xsd:element name="referenceDocumentTypeCode" type="${xsd:normalizedString,dd:OriginEntryFull.referenceFinancialDocumentTypeCode}"/>
    <xsd:element name="referenceOriginationCode" type="${xsd:normalizedString,dd:OriginEntryFull.referenceFinancialSystemOriginationCode}"/>
    <xsd:element name="referenceDocumentNumber" type="${xsd:normalizedString,dd:OriginEntryFull.referenceFinancialDocumentNumber}"/>
    <xsd:element name="documentReversalDate" type="${xsd:date,dd:OriginEntryFull.financialDocumentReversalDate}"/>
    <xsd:element name="encumbranceUpdateCode" type="${xsd:normalizedString,dd:OriginEntryFull.transactionEncumbranceUpdateCode}"/>

    <!-- trailer -->
    <xsd:element name="totalRecords" type="xsd:integer"/>
    <xsd:element name="totalAmount" type="xsd:decimal"/>

    <!-- detail -->
    <xsd:element name="createDate" type="${xsd:date, dd:CollectorDetail.createDate}" />
    <xsd:element name="collectorDetailSequenceNumber" type="${xsd:normalizedString,dd:CollectorDetail.collectorDetailSequenceNumber}"/>
    <xsd:element name="detailText" type="${xsd:normalizedString,dd:CollectorDetail.collectorDetailNoteText}"/>
    <xsd:element name="amount" type="${xsd:decimal,dd:CollectorDetail.collectorDetailItemAmount}"/>
 
    <!-- definition of complex type elements -->

        <xsd:complexType name="headerType">
            <xsd:all>
               <xsd:element maxOccurs="1" minOccurs="1" ref="chartOfAccountsCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="organizationCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="transmissionDate" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="batchSequenceNumber" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="personUserId" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="emailAddress" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="campusCode"/>
	           <xsd:element maxOccurs="1" minOccurs="1" ref="phoneNumber"/>
               <xsd:element maxOccurs="1" minOccurs="1" ref="mailingAddress"/>
               <xsd:element maxOccurs="1" minOccurs="1" ref="departmentName"/>
            </xsd:all>
        </xsd:complexType>

        <xsd:complexType name="detailType">
            <xsd:all>
               <xsd:element maxOccurs="1" minOccurs="1" ref="universityFiscalAccountingPeriod" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="universityFiscalYear" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="createDate" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="chartOfAccountsCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="accountNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="subAccountNumber" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="objectCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="subObjectCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="balanceTypeCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="objectTypeCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="collectorDetailSequenceNumber" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="originationCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="documentTypeCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="documentNumber" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="amount" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="detailText" />
            </xsd:all>
        </xsd:complexType>

        <xsd:complexType name="trailerType">
            <xsd:all>
		        <xsd:element ref="totalRecords" />
		        <xsd:element ref="totalAmount" />
            </xsd:all>
        </xsd:complexType>
 
        <xsd:complexType name="glEntryType">
            <xsd:all>
               <xsd:element maxOccurs="1" minOccurs="0" ref="universityFiscalYear" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="chartOfAccountsCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="accountNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="subAccountNumber" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="objectCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="subObjectCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="balanceTypeCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="objectTypeCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="universityFiscalAccountingPeriod" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="documentTypeCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="originationCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="documentNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="transactionEntrySequenceId" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="transactionLedgerEntryDescription" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="transactionLedgerEntryAmount" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="debitOrCreditCode" />
               <xsd:element maxOccurs="1" minOccurs="1" ref="transactionDate" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="organizationDocumentNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="projectCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="organizationReferenceId" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="referenceDocumentTypeCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="referenceOriginationCode" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="referenceDocumentNumber" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="documentReversalDate" />
               <xsd:element maxOccurs="1" minOccurs="0" ref="encumbranceUpdateCode" />
            </xsd:all>
        </xsd:complexType>

        <xsd:complexType name="batchType">
            <xsd:sequence>
                <xsd:element name="header" type="headerType"/>
                <xsd:sequence maxOccurs="unbounded">
                    <xsd:element minOccurs="0" maxOccurs="1" name="glEntry" type="glEntryType"/>
                    <xsd:element minOccurs="0" maxOccurs="1" name="detail" type="detailType"/>
                </xsd:sequence>
                <xsd:element name="trailer" type="trailerType"/>
            </xsd:sequence>
        </xsd:complexType>
        
    <xsd:element name="batch" type="batchType"/>

</xsd:schema>

=== r351574nc3/kfs-overlay-reference/config/target/classes/work/staging/gl/collectorXml/gl_collector1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Copyright 2005-2009 The Kuali Foundation
	
	Licensed under the Educational Community License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	http://www.opensource.org/licenses/ecl2.php
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->
<batch xmlns="http://www.kuali.org/kfs/gl/collector"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.kuali.org/kfs/gl/collector @externalizable.static.content.url@/xsd/gl/collector.xsd" >
	<header>
		<chartOfAccountsCode>IN</chartOfAccountsCode>
		<organizationCode>MDEP</organizationCode>
		<transmissionDate>2005-10-05</transmissionDate>
		<batchSequenceNumber>0</batchSequenceNumber>
		<personUserId>kul</personUserId>
		<emailAddress>knoreceipt-l@indiana.edu</emailAddress>
		<campusCode>BL</campusCode>
		<phoneNumber>123-456-7890</phoneNumber>
		<mailingAddress>1500 Berkeley</mailingAddress>
		<departmentName>Kuali Developers</departmentName>
	</header>
	<glEntry>
		<universityFiscalYear>2006</universityFiscalYear>
		<chartOfAccountsCode>BL</chartOfAccountsCode>
		<accountNumber>1031400</accountNumber>
		<subAccountNumber>ADV</subAccountNumber>
		<objectCode>3000</objectCode>
		<subObjectCode>WAC</subObjectCode>
		<balanceTypeCode>AC</balanceTypeCode>
		<objectTypeCode>EX</objectTypeCode>
		<universityFiscalAccountingPeriod>06</universityFiscalAccountingPeriod>
		<documentTypeCode>ID03</documentTypeCode>
		<originationCode>01</originationCode>
		<documentNumber>1000000</documentNumber>
		<transactionEntrySequenceId>1</transactionEntrySequenceId>
		<transactionLedgerEntryDescription>Description</transactionLedgerEntryDescription>
		<transactionLedgerEntryAmount>300.00</transactionLedgerEntryAmount>
		<debitOrCreditCode>C</debitOrCreditCode>
		<transactionDate>2005-10-05</transactionDate>
		<organizationDocumentNumber>ODN</organizationDocumentNumber>
		<projectCode>BAT</projectCode>
		<organizationReferenceId>ORI</organizationReferenceId>
		<referenceDocumentTypeCode>ID03</referenceDocumentTypeCode>
		<referenceOriginationCode>01</referenceOriginationCode>
		<referenceDocumentNumber>1234</referenceDocumentNumber>
		<documentReversalDate>2005-10-31</documentReversalDate>
		<encumbranceUpdateCode>D</encumbranceUpdateCode>
	</glEntry>
	<detail>
		<universityFiscalAccountingPeriod>06</universityFiscalAccountingPeriod>
		<universityFiscalYear>2006</universityFiscalYear>
		<chartOfAccountsCode>BL</chartOfAccountsCode>
		<accountNumber>1031400</accountNumber>
		<subAccountNumber>ADV</subAccountNumber>
		<objectCode>3000</objectCode>
		<subObjectCode>WAC</subObjectCode>
		<collectorDetailSequenceNumber>47</collectorDetailSequenceNumber>
		<originationCode>01</originationCode>
		<documentTypeCode>ID03</documentTypeCode>
		<documentNumber>1000000</documentNumber>
		<amount>1000000</amount>
		<detailText>Line 1b</detailText>
		<createDate>2007-08-01</createDate>
		<balanceTypeCode>AC</balanceTypeCode>
		<objectTypeCode>EX</objectTypeCode>
	</detail>
	<trailer>
		<totalRecords>2</totalRecords>
		<totalAmount>300.00</totalAmount>
	</trailer>
</batch>
